project:
  type: website

website:
  title: "Olivier Leroy"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/defuneste
      - icon: mastodon
        href: https://fosstodon.org/@defuneste
format:
  html:
    theme: United
    css: styles.css

