project:
  type: website

website:
  title: "Olivier Leroy"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/defuneste
      - icon: mastodon
        href: https://fosstodon.org/@defuneste
      - icon: linkedin
        href: https://www.linkedin.com/in/olivier-leroy-r/
  page-footer: 
    right:
    - icon: github
      href: https://github.com/defuneste/btl
format:
  html:
    theme: United
    css: styles.css

